### ISSUE TITLE
Date picker validation error message

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/design-gc-digital-talent#14]
## Details

Design and develop date validation criteria for the Date Picker. The Date Picker component does not announce an error message when an invalid date is entered (e.g., February 30, 2031).

Tester Feedback

While updating the user resume with a new education experience, there is a required form of selecting the start date of your education, and basically, none of the commands for my program works to select the specific date that I wanted in order to continue to the next step. Because neither the show links command nor the mouse grid command worked, it was impossible trying to select a specific date for the education part of the resume. I would recommend making it a bit more compatible with one or more commands so it's easier to access in general.

## Potential Solution

 - Identify and described what part of the date (day, month, year) is in error.

 - I think it would definitely make sense to say something like, so for instance, if the day is invalid in February, then I think it would be best to say enter a valid day. If that's the only part of the, if that's the only part of the date that's incorrect, I would announce the part that's incorrect. Relevant WCAG Criteria: 3.3.1 Error Identification.

Related issue: https://github.com/GCTC-NTGC/gc-digital-talent/discussions/6652

**Comment by gobyrne** [comment]
Worked with Lee and Eric to break this into actionable tickets. Closing this one.
