### ISSUE TITLE
Revisit table filters page

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/design-gc-digital-talent#20]
Eric says the filters that ended up being used in the table filter dialogue were all react-select component, but that the original designs were more varied. Designers, please take a look!

We are also working on this filter dialogue in this related issue:
https://github.com/GCTC-NTGC/gc-digital-talent/issues/4995

**Comment by gobyrne** [comment]
@substrae can you check this:

1. Make sure figma and prod match
2. Make sure you're happy with prod implementation.

**Comment by substrae** [comment]
@gobyrne Gonna toss this one to @Jerryescandon, as he was the original designer. If you need component guidance, tag or ping me again.

**Comment by gobyrne** [comment]
This has changed a lot since implementation and this issue is now stale. Closing
