### ISSUE TITLE
Clearer visual distinction between accordion button and a link

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/design-gc-digital-talent#33]
### 

## 🕵️‍♀️ Detail 

**AT Configuration**

- OS Magnification with Chrome on Mac 

**Tester Feedback:**

- I was not sure what the underlined linked text "Show this experience's details" (e.g. collapsible/ accordions) would do. The arrow pointed towards the text. I thought it would open a new page and then it was not an accordion. Putting the arrow next to the underlined linked text "Show this experience's details" up or down would indicate it was an accordion.

**💻Related WCAG Criteria:**

2.4.4.: he [purpose of each link](https://w3c.github.io/wcag/understanding/link-purpose-in-context#dfn-link-purpose) can be determined from the link text alone or from the link text together with its [programmatically determined link context](https://w3c.github.io/wcag/understanding/link-purpose-in-context#dfn-programmatically-determined-link-context), except where the purpose of the link would be [ambiguous to users in general](https://w3c.github.io/wcag/understanding/link-purpose-in-context#dfn-ambiguous-to-users-in-general).

  
## Screen capture:

![Image](https://user-images.githubusercontent.com/101275838/263758048-956fed71-d0fa-41ad-b798-0821621687a3.png)

##🧪 Testing Steps:

1. Navigate to the Review your résumé section of an application using OS magnification. 
2. Observe the underlined "Show this experience" collapsible text.
3. Activate the underlined text.

Could not reproduce the second Tester issue.. 

## 🌟 Potential solutions

- Remove underline from Accordion header 

 - [Related  accordion issues 
](https://github.com/GCTC-NTGC/gc-digital-talent/issues?q=is%3Aissue+is%3Aopen+accordions)

**Comment by gobyrne** [comment]
@substrae I think we addressed this to the extent desired, right? Can you comment with a short reminder of where we landed and close this?

**Comment by substrae** [comment]
@gobyrne Yeah, we've gone through and made a handful of changes to `details` elements, though the arrow direction is not one of them.

`accordions`/`details`/`expand-collapse`/whatever else you want to call them have had their underline removed across the site, however there is a different component (😓) that has yet to be updated with those changes (@esizer might have more info for you there), which is what you're seeing inside of the experience cards.

**Comment by gobyrne** [comment]
Changes have been made, we can revisit if it comes up again.
