### ISSUE TITLE
📝  Update "Edit Language copy for language  proficiency  level

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/design-gc-digital-talent#35]
✨ Details 
This update changes duplicate phrasing on the page for both consistency and clarity.

🗃️ Requirements

"Second Language proficiency level" instructive copy 

 - Remove the duplicate `find out `text.

**Comment by gobyrne** [comment]
Seems to be fixed, closing:

![Image](https://github.com/GCTC-NTGC/design-gc-digital-talent/assets/2494551/1ecad7d2-ddc0-4a9f-97db-59e5c54af48c)

**Comment by RM-1978** [comment]
Hi @gobyrne,  could you clarify what the requirement is on this one? Do you want a rewritten sentence for: "you can **find out** your levels....self-assessment?"
