### ISSUE TITLE
Some colours are too close to stoplight colors

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/design-gc-digital-talent#37]
## What is going on?

It's come up several times now that some of the colours in the new platform theme are too close to stoplight colors.

Dev team brought it up once and flagged it as a bug, when in fact the buttons were in fact the tertiary colour.

https://github.com/GCTC-NTGC/gc-digital-talent/issues/8461#issuecomment-1814830062

On a separate instance, DCM asked if there was "An error on the candidate's career timeline"? once again, it is just the tertiary colour being mistaken for an error colour.

<details><summary>Screenshot</summary>
<p>

![Image](https://github.com/GCTC-NTGC/design-gc-digital-talent/assets/16977254/df87dfc4-0125-4c7a-a0ef-f4ebfc56ff11)

</p>
</details> 

## Proposed solution

We should reconsider the current tertiary (and quaternary in Jerbo's opinion) and maybe opt for something a little bit further away from the "error-red"

**Comment by gobyrne** [comment]
@substrae over to you.

**Comment by substrae** [comment]
@gobyrne We knew this was going to be a problem coming out of the branding exercise. `tertiary`, `quaternary`, and `quinary` are red, yellow, and green respectively.

> It's come up several times now that some of the colours in the new platform theme are too close to stoplight colors.

I haven't been made aware that this has happened "several" times. The few times it has happened, it was the result of us migrating the admin UI from the `admin` theme to the core theme. The issue you've linked is one such issue.

That all said, "reconsider the current tertiary (and quaternary in Jerbo's opinion) and maybe opt for something a little bit further away from the 'error-red'" is a massive undertaking we're not prepared or resourced to do right now. We deliberately avoid using those three colors in instances where they might be misconstrued, so I'm not very worried about this right now. If we want to take another look at the branding choices when Brooke is back, I'm happy to facilitate that, but it will involve us rebuilding a significant number of both web and digital stationary materials (decks, templates, etc.).
