### ISSUE TITLE
Email notification - Confirmation email

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/design-gc-digital-talent#44]
## User Story
As a user, I want to receive a confirmation email, to make sure I typed my email correctly.

As an admin, I want users to confirm access to their email address and so I know I can communicate with them using it.

## Details
On registration (create account), we want to confirm the users email address that they use to access the site.

## Trigger:
Registration, or "request new confirmation email" link clicked

## Condition:
User has started, but not yet submitted an application (status == draft) for the opportunity that is closing.

## Email copy
@marc-donofrio to-do. Feel free to use pseudocode to include data elements your email template. For example <user name> or <closing date-time>.

**Source email address:** (what is our email?)

**Email subject:**

**Email body:**

**Comment by marc-donofrio** [comment]
Email: noreply@talent.canada.ca
Subject:  {{Site_name}} email activation

Hi {{contact.name}},

A new {{Site_name}} account has been created for you.

Click the url below to activate your account and select a password!

{{activation_url}}

If the above URL does not work try copying and pasting it into your browser. If you continue to have problems, please feel free to contact us.

Regards,
{{helpdesk_name}}
{{helpdesk_URL}}
