### ISSUE TITLE
Application copy update

### ISSUE THREAD

**Issue by RM-1978** [GCTC-NTGC/design-gc-digital-talent#47]
## 🔤 Copy

Adjust application copy with the TBS Editing and Translation team for consistency in both languages. 

## 🕵️ Details

Once a workflow goes into the copy pipeline it follows these steps: 

1. A screen capture of each page in the flow or pattern is taken and added to a Word document for context because the editing team works with departmentally issued OS 365 applications.
2.  The copy text is extracted into text-based wireframes that complement each screen capture. This is done so that the editors and translators can work with the text-based wireframes.    
3.  Send document over to the team as part of an Editing and translation request.  
4. Editing team does a consistency review and makes recommendations.
5. Review with Lauren. 
6. Final proofing and approvals
7. Translation. 
8. Code integration.

## 🎨 Design File

there are several design file now with different pieces of this flow. 

## 🙋‍♀️ Proposed Implementation

1. Review, approve and implement the proofed English copy below. 

  [GCDT Application Pattern_ proofread w bold_ 01-08-2024_GOB_dragon.docx…]()
   
2.  Review, approve and implement the revised translation when it is ready.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the copy has been added or updated appropriately.

- [ ] English copy is updated for consistency. 
- [ ] French copy is revised for consistency to match the new English copy.

**Comment by RM-1978** [comment]
@gobyrne, for implementation approval:
[FINAL-Simplified copy Application workflow-EN.docx](https://github.com/GCTC-NTGC/design-gc-digital-talent/files/14312366/FINAL-Simplified.copy.Application.workflow-EN.docx)
[FINAL-Simplified copy Application workflow-FR-REV-NG.docx](https://github.com/GCTC-NTGC/design-gc-digital-talent/files/14312367/FINAL-Simplified.copy.Application.workflow-FR-REV-NG.docx)

**Comment by gobyrne** [comment]
I created a separate dev ticket for this closing
